### ISSUE TITLE
adjusting min slider value not working

### ISSUE THREAD

**Issue by ebgoldstein** [2320sharon/Streamlit_Sniffer#10]
Adjusting the min slider value does not influence the slider. 
Adjusting max slider value does work.

(Firefox + Linux)

**Comment by 2320sharon** [comment]
Thanks for reporting this issue. Let me see if I can reproduce it.

**Comment by 2320sharon** [comment]
I attempted to reproduce this issue using the the version of Sniffer online at https://2320sharon-streamlit-sniffer-sniffer-h9knr1.streamlitapp.com/ with both google chrome and firefox on my windows machine and I could not recreate the issue. Can you provide any more details about when this bug appeared?

**Comment by ebgoldstein** [comment]
i must be going crazy...
![sniffer](https://user-images.githubusercontent.com/5330599/197648090-dc3aef1f-4450-4e42-be77-100b42e9a2c7.gif)

**Comment by ebgoldstein** [comment]
if you can't reproduce it, feel free to close the issue b/c it is probably just me..

**Comment by ebgoldstein** [comment]
this is on the streamlit web app.. its the exact same via localhost.. bizarre.. must be something on my end..

**Comment by 2320sharon** [comment]
Thank you for the gif. I was able to reproduce the bug

**Comment by 2320sharon** [comment]
Let me fix that right away.

**Comment by 2320sharon** [comment]
I just made an update that should have fixed the bug. Let me know if it worked for you

**Comment by ebgoldstein** [comment]
works! thank you @2320sharon
